### ISSUE TITLE
stubgen script name conflicts with mypy

### ISSUE THREAD

**Issue by cgevans** [MusicalNinjas/pyo3-stubgen#8]
Mypy also has a `stubgen` script, so each package will overwrite the other's when installed.  It might make sense to rename the script here to `pyo3-stubgen`.

**Comment by MusicalNinjaDad** [comment]
Good catch. Mypy's stubgen influenced the naming, but I hadn't thought of that conflict ...
I'll put a v0.4.0 together with the change this evening.
